version: "3.7"
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: "./backend"
      target: production
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    command: node dist/main.js
    ports:
      - 5555:5555
  postgres:
    image: "postgres:14-alpine"
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - pet-hero-postgres:/var/lib/postgresql/data
  frontend:
    build:
      dockerfile: Dockerfile.prod
      context: ./frontend
      args:
        - REACT_APP_API_URL=http://localhost:5555
    ports:
      - "8080:80"

volumes:
  pet-hero-postgres:
