version: "3.7"
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: "./backend"
      # Only will build development stage from our dockerfile
      target: development
    volumes:
      - ./backend:/app
    environment:
      FRONT_APP_URL: http://localhost
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    # Run a command against the development stage of the image
    command: npm run start:dev
    ports:
      - 5555:5555
      - 8081:8081

  postgres:
    image: "postgres:14-alpine"
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - pet-hero-postgres:/var/lib/postgresql/data

  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    environment:
      REACT_APP_API_URL: "http://localhost/api"
    volumes:
      - ./frontend/src:/app/src


