version: "3.9"
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: "./backend"
      # Only will build development stage from our dockerfile
      target: development
    volumes:
      - ./backend:/app
      - /certs:/etc/nginx/certs
    environment:
      FRONT_APP_URL: https://pethero.test
      SSL_CRT_FILE: /etc/nginx/certs/pethero.test.crt
      SSL_KEY_FILE: /etc/nginx/certs/pethero.test.key
      CERT_NAME: pethero.test

    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    # Run a command against the development stage of the image
    command: npm run start:dev
    ports:
      - 5555:5555
      - 8081:8081

  postgres:
    image: "postgres:14-alpine"
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"

  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    environment:
      REACT_APP_API_URL: "https://api.pethero.test"
      HTTPS: true
      SSL_CRT_FILE: /etc/nginx/certs/pethero.test.crt
      SSL_KEY_FILE: /etc/nginx/certs/pethero.test.key
      CERT_NAME: pethero.test

    ports:
      - 3333:3333
    volumes:
      - ./frontend/src:/app/src
      - /certs:/etc/nginx/certs
