const loginFields = [
  {
    labelText: "Email address",
    labelFor: "email",
    id: "email",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Email address",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
  },
];

const signupFields = [
  {
    labelText: "Email address",
    labelFor: "email",
    id: "email",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Email address",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
  },
  {
    labelText: "Confirm Password",
    labelFor: "confirm-password",
    id: "confirm-password",
    name: "confirm-password",
    type: "password",
    autoComplete: "confirm-password",
    isRequired: true,
    placeholder: "Confirm Password",
  },
];

const profileField = [
  {
    labelText: "Name",
    labelFor: "name",
    id: "name",
    name: "name",
    type: "text",
    autoComplete: "nickname",
    isRequired: true,
    placeholder: "George R. Schwartz",
  },
  {
    labelText: "Gender",
    labelFor: "gender",
    id: "gender",
    name: "gender",
    type: "text",
    autoComplete: "sex",
    isRequired: true,
    placeholder: "They",
  },
  {
    labelText: "age",
    labelFor: "age",
    id: "age",
    name: "age",
    type: "number",
    autoComplete: "off",
    isRequired: true,
    placeholder: "21",
  },
  {
    labelText: "Mobile",
    labelFor: "mobile",
    id: "mobile",
    name: "mobile",
    type: "number",
    autoComplete: "tel-local",
    isRequired: true,
    placeholder: "91234567",
  },
  {
    labelText: "Postal Code",
    labelFor: "postalcode",
    id: "postalcode",
    name: "postalcode",
    type: "number",
    autoComplete: "postal-code",
    isRequired: true,
    placeholder: "666666",
  },
  {
    labelText: "Address",
    labelFor: "address",
    id: "address",
    name: "Address",
    type: "text",
    autoComplete: "address-line1",
    isRequired: true,
    placeholder: "Upper Riverside Road",
  },
  {
    labelText: "Property Type",
    labelFor: "property_type",
    id: "property_type",
    name: "property_type",
    type: "text",
    autoComplete: "no",
    isRequired: true,
    placeholder: "HDB",
  },
];

export { loginFields, signupFields };
